package graficos;

import java.awt.Frame;

import javax.swing.JFrame;

public class CreandoMarcos {

	public static void main(String[] args) {
		
		miMarco marco1=new miMarco();
		marco1.setVisible(true); //AL INSTANCIAR UN MARCO ,HAY Q HACERLO VISIBLE ,SI NO NO SE VERIA ,YA QUE SOLO LA CREAMOS 
		
		marco1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //LE DECIMOS LO QUE TIENE QUE HACER CUANDO SE CIERRE,SI NO LO INDICAMOS
		//EL PROGRAMA SEGUIRIA EN EJECUCION ,EL METODO EXIGE UNA CONSTANTE DE LA CLASE,Y LA CONSTANTE PERTENECE A JFRAME

	}

}

class miMarco extends JFrame { //JFRAME ES LA CLASE PARA CREAR VENTANAS ,CREAMOS UNA CLASE QUE HEREDE DE ESTA PARA COGER SUS METODOS

	public miMarco() {

		//setSize(500, 300);//METEMOS EN EL CONSTRUCTOR EL METODO PARA ESTABLECER EL TAMAÑO  DE LA VENTANA PARA Q TODAS LAS INSTANCIAS LAS TENGAN

		//setLocation(500, 300);//UBICAMOS LA POSICION DE LA VENTANA
		
		setBounds(500, 300, 550, 250);//ESTE METODO NOS PERMITE DARLE EL TAMAÑO Y LA POSICION A LA VEZ
		
		//setResizable(false);//METODO PARA PERMITIR LA REDIMENSION O NO DE LA VENTANA
		
		//setExtendedState(Frame.MAXIMIZED_BOTH);//PARA ABRIR LA VENTANA A PANTALLA COMPLETA ,EL METODO EXIGE UNA CONSTANTE DE LA CLASE
		
		setTitle("Mi Ventana"); //PARA ESTABLECER UN TITULO
		
	}
}
